#!/bin/sh
# prpcUtils sh script
#                          Copyright 2017  Pegasystems Inc.                           
#                                 All rights reserved.                                 
# This software has been provided pursuant to a License Agreement containing restrictions
# on its use. The software contains valuable trade secrets and proprietary information of
# Pegasystems Inc and is protected by federal copyright law.It may not be copied, modified,
# translated or distributed in any form or medium, disclosed to third parties or used in 
# any manner not provided for in  said License Agreement except with  written
# authorization from Pegasystems Inc.


# Wrapper for the command line prpcUtils contained in prpcUtils.xml

# shellcheck source=posixUtils.sh
. "$(dirname "$0")/../posixUtils.sh"
$JAVA_HOME="C:\Program Files\Java\jre1.8.0_211"

CURRENT_SCRIPT=$(dirname "$0")

usage() {
	echo "prpcServiceUtils.sh export | expose | hotfix | import | getStatus | rollback | manageRestorePoints | updateAccessGroup | updateDASS |  help [options...]"
	echo ""
	echo "Options:"	
	echo "  --connProp                 FilePath to connection.properties to operate on multiple instances."
	echo "  --propFile                 Location of prpcServiceUtils.properties file. Defaults to ./prpcServiceUtils.properties"
	echo "  --poolSize                 Thread pool size"
	echo "  --requestTimeOut           Request TimeOut"
	echo "  --jobIdFile                Path to the JobIds file generated by EXPORT/IMPORT/EXPOSE/HOTFIX operation"		
	echo "  --operationName            Operation name to be queried for getStatus. import, export, expose, and rollback are the valid operation names"
	echo "  --artifactsDir             Specify directory where all the service response artifacts like attachments, service operation logs are stored."
	echo "  --processFailStrategy      Specify the failure strategy to use in case of multiple instances."
	echo "                             FAIL_PROCESS_ON_SINGLE_SYSTEM_FAILURE (Fails the process when the requested operation fails on at least one instance)"
	echo "                             FAIL_PROCESS_ON_ALL_SYSTEM_FAILURE (Fails the process only when the requested operation fails on all instances)."
	echo "                             Default value is FAIL_PROCESS_ON_SINGLE_SYSTEM_FAILURE"
	exit 1
}

if [ -z "$JAVA_HOME" ] ; then
        echo "The JAVA_HOME environment variable must be defined."
        exit 1
fi

# get tool type (export, import, etc.)
# tool type must coincide with an ant target in prpcUtils.xml
TOOL_TYPE=""
case "$1"
in
        "export")				TOOL_TYPE="export";;
        "expose")				TOOL_TYPE="expose";;
        "hotfix")				TOOL_TYPE="hotfix";;
		"import")        	    TOOL_TYPE="import";;
		"getStatus")        	TOOL_TYPE="getstatus";;
		"rollback")    			TOOL_TYPE="rollback";;
		"manageRestorePoints")  TOOL_TYPE="manageRestorePoints";;
		"updateAccessGroup")  	TOOL_TYPE="updateAccessGroup";;
		"updateDASS")  	        TOOL_TYPE="updateDASS";;
        "help")					usage;;
        "--help")				usage;;
        *)               		echo "Unknown tool type $1"
                         		usage;;
esac
shift


ANT_PROPS=""
while [ "$1" != "" ]
do
        case "$1"
        in
                "--requestTimeOut")  shift
								 ANT_PROPS="$ANT_PROPS -Dprpcserviceutils.request.timeout=\"$(escape "$1")\"";;
				"--poolSize") shift
								 ANT_PROPS="$ANT_PROPS -Dprpcserviceutils.pool.size=\"$(escape "$1")\"";;
				"--connPropFile") shift
								 ANT_PROPS="$ANT_PROPS -Dprpcserviceutils.connection.filepath=\"$(escape "$1")\"";;
                "--propFile")    shift
                                 ANT_PROPS="$ANT_PROPS -Dprpc.service.utils.custom.property.filepath=\"$(escape "$1")\"";;
				"--jobIdFile") shift
								 ANT_PROPS="$ANT_PROPS -Doperation.specific.file.path=\"$(escape "$1")\"";;
				"--operationName") shift
								 ANT_PROPS="$ANT_PROPS -Dgetstatus.operationName=\"$(escape "$1")\"";;
				"--artifactsDir") shift
								 ANT_PROPS="$ANT_PROPS -Dservice.responseartifacts.dir=\"$(escape "$1")\"";;
				"--processFailStrategy") shift
								 ANT_PROPS="$ANT_PROPS -Dservice.processFailStrategy=\"$(escape "$1")\"";;
                "--help")        usage;;
                *)               echo "Unknown setting $1"
                                 usage;;
        esac
        shift
done

TIMESTAMP=$(date +'%h-%d-%Y-%H-%M-%S')
ANT_PROPS="$ANT_PROPS -Dprpc.service.util.action=$TOOL_TYPE"
ANT_PROPS="$ANT_PROPS -Dlogfile.timestamp=$TIMESTAMP"
logfile=$CURRENT_SCRIPT/logs/CLI-prpcServiceUtils-log-$(date +'%h-%d-%Y-%H-%M-%S').log
mkdir -p "$CURRENT_SCRIPT/logs"
# Run Ant, given the configuration we collected
run eval "\"$(dirname "$0")/../bin/ant\"" "$ANT_PROPS" -f "\"$CURRENT_SCRIPT/prpcServiceUtilsWrapper.xml\"" performOperation 2>&1 \| tee "$logfile"


if [ "$pipestatus_1" -ne 0 ] ; then
        echo "Ant Process returned a non 0 value"
        exit 1
	else
		exit 0
fi
